name: mosl_network
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  protobuf: ^4.0.0
  path_provider: ^2.0.0
  http_parser: ^4.0.2
  image_picker:       # Latest version as of now
  image_cropper:
    git:
      url: https://github.com/hnvn/flutter_image_cropper.git
      path: image_cropper
      ref: master
  # Latest version
  permission_handler:
  device_info_plus:
  base_network:
    path: packages/base_network
  connectivity_plus: ^6.1.4
  dio_cache_interceptor:
    git:
      url: https://github.com/mofsl-flutter/dio_cache_interceptor.git
      ref: 590820f56664b3c3559c4a0f162c33de41e538f3
      path: dio_cache_interceptor

  dio_cache_interceptor_hive_store:
    git:
      url: https://github.com/mofsl-flutter/dio_cache_interceptor.git
      ref: e5a827619f3e872c7e47d56e0e8430148b9eb336
      path: dio_cache_interceptor_hive_store


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
